package com.mx.jsen.application.client.registrarUsuario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.13
 * 2017-10-28T14:08:24.494-05:00
 * Generated source version: 3.1.13
 * 
 */
@WebService(targetNamespace = "http://registrarusuario.webservice.application.jsen.mx.com/", name = "RegistrarUsuarioWS")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistrarUsuarioWS {

    @WebMethod
    @RequestWrapper(localName = "consultarLada", targetNamespace = "http://registrarusuario.webservice.application.jsen.mx.com/", className = "com.mx.jsen.application.client.registrarUsuario.ConsultarLada")
    @ResponseWrapper(localName = "consultarLadaResponse", targetNamespace = "http://registrarusuario.webservice.application.jsen.mx.com/", className = "com.mx.jsen.application.client.registrarUsuario.ConsultarLadaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.mx.jsen.application.client.registrarUsuario.TblLada> consultarLada();

    @WebMethod
    @RequestWrapper(localName = "registrarUsuario", targetNamespace = "http://registrarusuario.webservice.application.jsen.mx.com/", className = "com.mx.jsen.application.client.registrarUsuario.RegistrarUsuario")
    @ResponseWrapper(localName = "registrarUsuarioResponse", targetNamespace = "http://registrarusuario.webservice.application.jsen.mx.com/", className = "com.mx.jsen.application.client.registrarUsuario.RegistrarUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String registrarUsuario(
        @WebParam(name = "correo", targetNamespace = "")
        java.lang.String correo,
        @WebParam(name = "numero", targetNamespace = "")
        java.lang.Long numero,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "lada", targetNamespace = "")
        java.lang.Long lada
    );
}
