
package com.mx.jsen.application.client.registrarUsuario;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-09T16:19:53.549-05:00
 * Generated source version: 3.1.12
 * 
 */
public final class RegistrarUsuarioWS_RegistrarUsuarioWSImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://registrarusuario.webservice.application.jsen.mx.com/", "registrarUsuarioService");

    private RegistrarUsuarioWS_RegistrarUsuarioWSImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RegistrarUsuarioService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RegistrarUsuarioService ss = new RegistrarUsuarioService(wsdlURL, SERVICE_NAME);
        RegistrarUsuarioWS port = ss.getRegistrarUsuarioWSImplPort();  
        
        {
        System.out.println("Invoking registrarUsuario...");
        java.lang.String _registrarUsuario_correo = "";
        java.lang.String _registrarUsuario_username = "";
        java.lang.String _registrarUsuario_password = "";
        java.lang.String _registrarUsuario__return = port.registrarUsuario(_registrarUsuario_correo, _registrarUsuario_username, _registrarUsuario_password);
        System.out.println("registrarUsuario.result=" + _registrarUsuario__return);


        }

        System.exit(0);
    }

}
