package com.mx.jsen.application.client.registrarUsuario;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-09T16:19:53.604-05:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "registrarUsuarioService", 
                  wsdlLocation = "http://localhost:8080/JsenLogica/ws/registrarUsuarioWs?wsdl",
                  targetNamespace = "http://registrarusuario.webservice.application.jsen.mx.com/") 
public class RegistrarUsuarioService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://registrarusuario.webservice.application.jsen.mx.com/", "registrarUsuarioService");
    public final static QName RegistrarUsuarioWSImplPort = new QName("http://registrarusuario.webservice.application.jsen.mx.com/", "RegistrarUsuarioWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/JsenLogica/ws/registrarUsuarioWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistrarUsuarioService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/JsenLogica/ws/registrarUsuarioWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegistrarUsuarioService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrarUsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrarUsuarioService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RegistrarUsuarioService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RegistrarUsuarioService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RegistrarUsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RegistrarUsuarioWS
     */
    @WebEndpoint(name = "RegistrarUsuarioWSImplPort")
    public RegistrarUsuarioWS getRegistrarUsuarioWSImplPort() {
        return super.getPort(RegistrarUsuarioWSImplPort, RegistrarUsuarioWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrarUsuarioWS
     */
    @WebEndpoint(name = "RegistrarUsuarioWSImplPort")
    public RegistrarUsuarioWS getRegistrarUsuarioWSImplPort(WebServiceFeature... features) {
        return super.getPort(RegistrarUsuarioWSImplPort, RegistrarUsuarioWS.class, features);
    }

}
